#!/bin/sh

RESTART_NAME=$PROMETHEUS_IMAGE_NAME

if [ -z $RESTART_NAME ]; then
    exit 0
fi

if ! type "docker" > /dev/null; then
  echo Docker not available, cannot restart Prometheus
  exit 0
fi

if [ ! -S "/var/run/docker.sock" ]; then
  echo Docker volume not mounted, cannot restart Prometheus
  exit 0
fi

PROM_CONTAINER_ID=$(docker ps | grep "$RESTART_NAME" | cut -d ' ' -f1)

if [ -z $PROM_CONTAINER_ID ]; then
    echo Could not find Prometheus container with image $RESTART_NAME, cannot restart Prometheus
    exit 0
fi

echo Restarting Prometheus at container ID: $PROM_CONTAINER_ID
docker kill --signal "SIGHUP" $PROM_CONTAINER_ID
echo Restart signal sent
